### ISSUE TITLE
GPL What?

### ISSUE THREAD

**Issue by mabels** [HaKr/rusty-core#1]
Hi,

i just saw your nice rust inspired library.
Is there any reason why you choosed the GPL license?
This selection of this license make it inpossible to use the work from you.

Is the any chance to change the license to AFL-2 or MIT?

thx

meno

**Comment by HaKr** [comment]
Thanks for your kind words.

No, no specific reason to pick the GPL license. Must have been the top ir
else the most familiar one.

I will have a look if I can change it to a more usable one.

Kind regards,
Harry de Kroon

Op di 18 jul. 2023 09:56 schreef Meno Abels ***@***.***>:

**Comment by HaKr** [comment]
Sorry that it took this long for such a minor change, but I've modified the license to be Expat (MIT)
